import express from 'express';
import dotenv from 'dotenv';
dotenv.config();
import cors from 'cors';
import morgan from 'morgan';
import helmet from 'helmet';
import bodyParser from 'body-parser';
import viewEngine from './configs/viewEngine';
import routes from './routes';
import connectDB from './configs/connectDB';
const app = express();
const port = process.env.PORT || 4000;
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cors());
app.use(morgan("dev"));
app.use(helmet());
viewEngine(app);
routes(app);
connectDB();
app.listen(port, () => console.log(`Server listening on http://localhost:${port}`));